WalletConnect/keys-server

.env.example, .github/workflows/intake.yml, .gitignore, src/main.rs, terraform/.terraform.lock.hcl, terraform/.tflint.hcl, terraform/README.md, terraform/backend.tf, terraform/ecs/main.tf, terraform/ecs/outputs.tf, terraform/ecs/variables.tf, terraform/main.tf, terraform/monitoring/main.tf, terraform/monitoring/variables.tf, terraform/provider.tf, terraform/variables.tf
* Spin up ECS service/load balancer
* Monitoring/Dashboard
* Intake process workflow
* fmt on app code
Couldn't properly test as Docker image not yet available
=> feat(infra): spin up service

src/main.rs
Route `/health` returns StatusCode 200
=> feat: Added health route

.github/workflows/ci_terraform.yml
=> feat(ci): add terraform ci

Cargo.lock, Cargo.toml, src/main.rs
=> feat: Remove dotenv

.github/workflows/cd.yml, .github/workflows/ci_terraform.yml, .github/workflows/release.yml, terraform/ecs/main.tf, terraform/ecs/variables.tf, terraform/main.tf, terraform/variables.tf
Adds image tagging
Resolves #23 
Not tested
=> feat(ci): Add image tagging and release

src/handlers/mod.rs
Merge after #53 
CAIP10 accounts length changed
=> feat: Adjust caip10 account lenght

Cargo.lock, src/handlers/identity/mod.rs, src/handlers/identity/unregister.rs
=> feat: Add act to unregister identity

Cargo.lock, terraform/ecs/main.tf
=> fix: Add second ecs instance

src/auth/cacao/payload.rs, src/stores/keys.rs
This reverts commit df9a806c63cb8913d5fcccb9555ace59f5268228.
=> Revert "feat: Ensure accounts stored as lowercase (#53)"

.github/actions/install-rust/action.yml, .github/actions/rust-cache-start/action.yml, .github/actions/rust-cache-stop/action.yml, .github/workflows/cd.yml, .github/workflows/ci-app.yml, .github/workflows/ci-infra.yml, .github/workflows/ci.yml
Automatically trigger a deployment from the CI workflow when suitable.
=> fix: trigger deploy from CI

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/workflows/intake.yml, .github/workflows/issues.yaml
- Update the project ID for `intake`
- Add PR validation on linked issues.
Resolves #82
=> feat: add project issues workflow, update project id

.github/workflows/dispatch_deploy.yaml, .github/workflows/dispatch_publish.yaml, .github/workflows/dispatch_validate.yaml, .github/workflows/event_pr.yaml, .github/workflows/event_release.yaml, .github/workflows/sub-app-check.yml, .github/workflows/sub-app-deploy.yml, .github/workflows/sub-cd.yml, .github/workflows/sub-ci.yml, .github/workflows/sub-infra-apply.yml, .github/workflows/sub-infra-check.yml, .github/workflows/sub-infra-plan.yml, .github/workflows/sub-publish-image.yml
=> fix: CI permissions

.github/workflows/dispatch_deploy.yaml, .github/workflows/dispatch_publish.yaml, .github/workflows/event_release.yaml, .github/workflows/sub-cd.yml, .github/workflows/sub-publish-image.yml
Fix release flows and ECR repository name
=> fix: release flows in CI

.github/workflows/dispatch_deploy.yaml, .github/workflows/dispatch_publish.yaml, .github/workflows/dispatch_validate.yaml, .github/workflows/sub-cd.yml, .github/workflows/sub-ci.yml, .github/workflows/sub-publish-image.yml
=> fix: publish flow

.github/workflows/dispatch_deploy.yaml, .github/workflows/dispatch_publish.yaml
=> fix: CI titles

.github/workflows/dispatch_publish.yaml, .github/workflows/event_release.yaml
Fix update version usage in CI
=> fix: update version usage

terraform/monitoring/panels/app/app_metric.libsonnet, terraform/monitoring/panels/app/identity/invalid_register_cacao.libsonnet, terraform/monitoring/panels/app/identity/invalid_unregister_jwt.libsonnet, terraform/monitoring/panels/app/identity/register.libsonnet, terraform/monitoring/panels/app/identity/resolved.libsonnet, terraform/monitoring/panels/app/identity/unregister.libsonnet, terraform/monitoring/panels/app/invite/invalid_register_jwt.libsonnet, terraform/monitoring/panels/app/invite/invalid_unregister_jwt.libsonnet, terraform/monitoring/panels/app/invite/register.libsonnet, terraform/monitoring/panels/app/invite/resolved.libsonnet, terraform/monitoring/panels/app/invite/unregister.libsonnet
Change from displaying raw data to `increase` with `avg_over_time`.
Deployed to `staging`
=> fix: display metric increase for Prometheus

src/lib.rs
Change the order in which the layers are applied to have `geoblock` at the beginning of the chain.
=> fix: apply geoblock at beginning of chain

terraform/inputs.tf, terraform/res_application.tf, terraform/res_dns.tf
- Replace the local copy of the geoIP database files with the shared on `main`.
- Update tf dependencies
Deployed to staging
=> fix: replace local copy of geoip db with shared one.

Cargo.lock, Cargo.toml
Update the utils dependency to 0.7.0
=> chore: update `utils` version

.github/workflows/event_pr.yaml
Removes the CI check for linked issues
NA
=> chore: remove linked issues check

terraform/monitoring/panels/docdb/available_memory.libsonnet
To fix [this issue](https://walletconnect.slack.com/archives/C05S6CH27HC/p1699050968628449)
Not tested
=> chore: reduce memory threshold to 1.5GB

Cargo.lock, Cargo.toml, src/config.rs, src/error.rs, src/handlers/identity/register.rs, src/lib.rs, src/state.rs
Updates to latest version of WalletConnectRust to support dynamically supporting chains.
Remaining work:
Not tested
=> fix: dynamic chain support

Cargo.lock, Cargo.toml, src/error.rs, src/lib.rs
Bump to latest shared deps versions.
Remaining work:
Existing tests
=> chore: bump deps

terraform/ecs/cluster.tf
Pins the otel image used to v0.3.0
Resolves # (issue)
=> chore: pin otel image version

terraform/ecs/cluster.tf
Changes otel container version to match the one used on the relay
Resolves # (issue)
=> chore: update version
