WalletConnect/keys-server

- src/auth/jwt/mod.rs
- src/auth/jwt/tests.rs
- src/handlers/invite/register.rs
- src/handlers/invite/unregister.rs
- src/stores/keys.rs
Adds missing error handling for jwt creation. Previously instead of error response there was `socket hang up` 
Resolves # (issue)
Added unit test. Verified manually to receive valid error response
> fix: Verify cacao without lowercase address

- Cargo.lock
- src/handlers/identity/mod.rs
- src/handlers/identity/unregister.rs
Previously one was able to unregister identity by simply calling unregister with payload from resolve identity. 
Resolves #51 
Manually
> feat: Unregister Identity with did-jwt

- src/auth/did.rs
- src/handlers/invite/mod.rs
Validates `InviteKeyClaims::iss` to be in [X25519](https://w3c-ccg.github.io/did-method-key/#x25519) format.
Resolves #49
Unit
>  feat: Ensure invite keys are in did:key format

- terraform/ecs/outputs.tf
- terraform/main.tf
- terraform/monitoring/dashboard.tf
- terraform/monitoring/variables.tf
Use load balancer ARN suffix in Grafana dashboard.
> fix: use lb arn suffix in grafana dashboard

- .github/workflows/deploy-infra.yml
The dispatch workflow event for `deploy_infra` lacks the `version` parameter which leads to failing deployments ("failed to normalize image reference").
Adds that parameter to enable manual infra deployments.
Not tested (CI)
> fix: add image version parameter to dispatch workflow event

- README.md
- justfile
- src/error.rs
- terraform/ecs/network.tf
- terraform/monitoring/dashboard.tf
- terraform/monitoring/panels/app/app_cpu_memory.libsonnet
- terraform/monitoring/panels/docdb/available_memory.libsonnet
- terraform/monitoring/panels/docdb/cpu.libsonnet
- terraform/monitoring/panels/docdb/low_mem_op_throttled.libsonnet
Rename `keyserver` to `keys-server` in human-readable strings.
Resource strings are kept untouched since that would force us to redeploy the whole infra.
Not tested
> chore: rename `keyserver` to `keys-server` in strings

- src/lib.rs
- terraform/ecs/cluster.tf
- Configure the Prometheus telemetry port in task definition to enable metrics export
- Output a warning on app start if telemetry is disabled
> fix: enable metrics export in ECS

- terraform/monitoring/panels/app/identity/invalid_register_cacao.libsonnet
- terraform/monitoring/panels/app/identity/invalid_unregister_jwt.libsonnet
- terraform/monitoring/panels/app/identity/register.libsonnet
- terraform/monitoring/panels/app/identity/resolved.libsonnet
- terraform/monitoring/panels/app/identity/unregister.libsonnet
- terraform/monitoring/panels/app/invite/invalid_register_jwt.libsonnet
- terraform/monitoring/panels/app/invite/invalid_unregister_jwt.libsonnet
- terraform/monitoring/panels/app/invite/register.libsonnet
- terraform/monitoring/panels/app/invite/resolved.libsonnet
- terraform/monitoring/panels/app/invite/unregister.libsonnet
Remove the `rate` function from the Prometheus queries to only show raw numbers
Deployed to `staging`
> fix: remove `rate` from Prometheus queries

- src/auth/cacao/payload.rs
- src/auth/cacao/tests.rs
Required by https://github.com/WalletConnect/walletconnect-specs/pull/139
The identity key will no longer be in Cacao resources but in the audience. In order to avoid breaking changes we accept both versions. If Identity Key is present in both resources and audience the latter is taken. 
Resolves #129 
Unit tests supported by data generated by Kotlin SDK
> feat: Allow taking identity key from audience

- .github/workflows/event_release.yaml
Add a task to display the version output from the `get-version` task in the release event handler
Resolves #132 
N/A
> chore: display actual version passed to the CD

- terraform/ecs/cluster_iam.tf
- terraform/inputs.tf
- terraform/res_application.tf
Use a local version of the GeoIP DB until a central one with the right permissions is deployed.
> fix: use local version of geoip db

- .github/workflows/dispatch_publish.yaml
- .github/workflows/event_release.yaml
Bumping `update-rust-version` CI action script to 2.1.5 [because of Cargo.lock issue](https://github.com/WalletConnect/actions/issues/20).
Resolves #149
Test plan in https://github.com/WalletConnect/actions/issues/20
> ci: bump update_rust_version to 2.1.5

- src/lib.rs
* Add `Method:DELETE` to cors layer to allow unregistering/deleting identity keys
Resolves #151
> fix: add cors on delete

- justfile
- src/handlers/identity/resolve.rs
- src/stores/keys.rs
- Implement timing traces to see what's slowing down requests.
- Refactor to avoid redundant `ResolveIdentityParams` struct.
- Add `fmt-imports` target to keep code formatting
Not tested
> fix: add timing traces

- Cargo.lock
- Cargo.toml
- justfile
- src/handlers/identity/resolve.rs
- src/lib.rs
- src/stores/keys.rs
#160 didn't have a unique per-request ID, this adds a span specifically for that.
Also supports the x-request-id ID for better tracing.
Also adds `just devloop` pipeline which adapts closer to Notify Server pipeline including running unit tests and `fmt-imports`
Not tested, but copied from https://github.com/WalletConnect/blockchain-api/commit/ab0a84a1a2a14230f189549fb3cfe1df9dbaec26
> fix: add x request

- justfile
- src/error.rs
Logs the HTTP errors.
Not tested
> fix: log HTTP errors

- .github/workflows/dispatch_deploy.yaml
This PR fixes the error on the manual dispatch of the [`Deploy` workflow](https://github.com/WalletConnect/keys-server/actions/workflows/dispatch_deploy.yaml) with the default empty image tag by making the following changes:
* Making the `Release Version` as an option with the following options:
* `latest` - latest release tag.
* `manual` - manual image tag version to deploy.
* Using the manual tag only when the `manual` option is chosen.
Tested by invoking the workflow from the branch.
> fix(ci): using the `latest` and `manual` image tag in the manual deploy

- .github/workflows/dispatch_deploy.yaml
I think same issue as https://github.com/WalletConnect/notify-server/pull/323. Cannot use `latest` in manual deploy:
```
CannotPullContainerError: pull image manifest has been retried 1 time(s): failed to resolve ref 139235753791.dkr.ecr.eu-central-1.amazonaws.com/keyserver:v1.0.1: 139235753791.dkr.ecr.eu-central-1.amazonaws.com/keyserver:v1.0.1: not found
```
Not tested
> fix: invalid tag on latest version deploy

- src/stores/keys.rs
Resolves the use of COLSCAN instead of IXSCAN.
With DocumentDB on a sparse index, you must use `$exists: true` in the query or else it will always use a COLSCAN: https://docs.aws.amazon.com/documentdb/latest/developerguide/functional-differences.html#functional-differences.sparse-index
[Slack conversation](https://walletconnect.slack.com/archives/C068RRL89HC/p1707334769713159)
[Slack conversation](https://walletconnect.slack.com/archives/C044SKFKELR/p1707335021051799)
Manually
> fix: query performance on DocumentDB

- Cargo.lock
- Cargo.toml
- src/handlers/identity/register.rs
- src/stores/keys.rs
Requires https://github.com/WalletConnect/WalletConnectRust/pull/59 to be released as assumed 0.26.1
> fix: lowercase addresses

- src/stores/keys.rs
Fixes the duplicate key detection check, without doing string matching (which was incorrect).
Also removes `identities.identity_key` from filter since we should get a conflict when trying to insert a duplicate identity key, rather than getting a conflict when trying to insert a duplicate account.
Resolves #177 
Not tested
> fix: duplicate key registration giving 500 error

- Cargo.lock
- Cargo.toml
- justfile
Prereq for https://github.com/WalletConnect/notify-server/pull/398
Remaining work:
Not tested
> fix: bump WalletConnectRust

- .github/workflows/dispatch_deploy.yaml
- .github/workflows/dispatch_publish.yaml
- .github/workflows/event_intake.yml
- .github/workflows/event_pr.yaml
- .github/workflows/event_release.yaml
- .github/workflows/sub-app-check.yml
- .github/workflows/sub-app-deploy.yml
- .github/workflows/sub-cd.yml
- .github/workflows/sub-infra-apply.yml
- .github/workflows/sub-infra-check.yml
- .github/workflows/sub-infra-plan.yml
- .github/workflows/sub-publish-image.yml
- .github/workflows/sub-validate.yml
- justfile
- terraform/ecs/cluster.tf
- terraform/ecs/cluster_autoscaling.tf
- terraform/ecs/variables.tf
- terraform/res_application.tf
- Fixes the math on ECS instance size calculation (copying from Notify Server), now it's actually 512.
- Downscales ECS task size and autoscaling on staging to be as minimal as possible (copying from Notify Server).
- Also downgraded Terraform Cloud config for DocumentDB size from `db.r6g.large` to `db.r5.large`
- Also uses `ubuntu-latest` runner to save costs
- Also updates `justfile` to auto-run Terraform formatting instead of just checking
Not tested
> fix: downscale ECS, staging env

- .github/workflows/dispatch_deploy.yaml
- .github/workflows/dispatch_publish.yaml
- .github/workflows/sub-cd.yml
Removes deployment window protection as we agreed that we didn't need this and it only caused problems as things were not deployed when we expected them to.
Not tested
> chore: remove deployment window

- terraform/monitoring/panels/docdb/available_memory.libsonnet
- terraform/res_application.tf
Since DocumentDB was downscaled, it violated the alarm. Adjusting alarm to fix. [Slack conversation](https://walletconnect.slack.com/archives/C058RS0MH38/p1710824505648449?thread_ts=1710824416.779259&cid=C058RS0MH38)
Also downscale ECS to minimum scale.
Not tested
> fix: reduce error threshold and downscale

- Cargo.lock
- Cargo.toml
Adds support for EIP-6492 signatures which are necessary for verification of our smart account.
Remaining work:
Not tested
> feat: EIP-6492
